# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            '@projectgheist'
tagline:          'A code developmenet blog'
description:      'Brain dump of code exploration'
url:              http://projectgheist.github.io/
baseurl:          /

author:
  name:           'ProjectGheist'
  url:            http://projectgheist.github.io/

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/projectgheist/projectgheist.github.io

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"